### ISSUE TITLE
[Feature Request] Support arbitrary PDB files

### ISSUE THREAD

**Issue by jmeier-absci** [a-r-j/VSCoding-Sequence#1]
Thanks for the great extension! This is helpful for visualizing PDB files in the RCSB.

I'd like to request a new feature: support for arbitrary PDB files. VSCode has access to the filesystem - it would be nice to click on a local PDB file and pull it up in the editor. Thanks!

**Comment by a-r-j** [comment]
Hi @jmeier-absci thanks for the request! I completely agree & I'm working on it. This is my first shot at writing an extension so bear with me 😅

**Comment by a-r-j** [comment]
Hi @jmeier-absci think I've figured it out. Update should be live on the [extension marketplace](https://marketplace.visualstudio.com/items?itemName=ArianJamasb.protein-viewer). Mind giving it a test drive & confirming it works as expected?

**Comment by NatureGeorge** [comment]
Hi! Appreciate your work. But the `Right-click open` seems only support `.pdb` suffix for now. It should be straightforward to add other suffixes like `.pdb.gz`, `.cif`, `.cif.gz` etc.
Besides, I notice that every single `Right-click open` behavior would start a whole new window for `Protein Viewer`. Maybe sometimes people would like to open multiple files in the same `Protein Viewer` window.

**Comment by a-r-j** [comment]
Hi @NatureGeorge thanks for this!

Wrt supporting additional file extensions, that should be straightforward and I can most likely take care of it today.

For opening multiple files, I'll have to think about the best way to handle it. My first thought is to support opening multiple files at once - I'm not quite sure how I'd go about adding a new file to an existing viewer through VSCode.

For the switching issue, I can check that out too. I'm not 100% sure on how to handle it - if it's poor execution on my part or the way that VSCode deals with background web panels (to save resources or something). If you have some familiarity, it'd be great if you could share 😁

**Comment by a-r-j** [comment]
Hey @NatureGeorge 

I've made the changes to support additional filetypes:

```
.pdb
.pdbqt
.mmcif
.gro
.xyz
.cif
.mol
.mol2
.sdf
```

I also believe I fixed the issue with the viewer resetting when switching panels.

I haven't quite figured out how to add files to an existing viewer - there is functionality in VSCode to update the HTML of the panel, but I believe it would force a reset of the viewer, so any customisation done before loading the second structure would be lost.

**Comment by NatureGeorge** [comment]
Wow. Thanks for your quick reply and update! @a-r-j 
I believe that adding files to an existing viewer via VS Code is quite difficult and may not be a crucial feature (since users can load other structures through Mol*'s `Open Files` button).

**Comment by a-r-j** [comment]
Hi @NatureGeorge you can now  (`0.0.6+`) select multiple files to open in the same viewer. You can also open the contents of folder in a single viewer. It's not quite the same as adding to a viewer but I think it's close enough to consider this closed :)
