### ISSUE TITLE
[Feature Request] Support for viewing general chemical structures (not just proteins)

### ISSUE THREAD

**Issue by hekima31** [a-r-j/VSCoding-Sequence#3]
Possible to add support for viewing general .xyz files not limited to proteins? Thank you.

**Comment by a-r-j** [comment]
Hiya @hekima31 :) We support:

```
.pdb
.pdbqt
.mmcif
.gro
.xyz
.cif
.mol
.mol2
.sdf
```

Are these not working for you? Which version are you on?

**Comment by a-r-j** [comment]
Hi @hekima31. Are you still having trouble? If not, I’ll close this issue.

**Comment by hekima31** [comment]
Hi @a-r-j, sorry for my delayed reply.
version: 0.0.4

I am still having the same issue. Attached a gif to demonstrate the issue if it helps.
![Reproducible](https://user-images.githubusercontent.com/55980431/145560835-e26aa0cf-f8ae-4975-a5dc-157be22a4ee4.gif)

**Comment by a-r-j** [comment]
Thanks! Looks like this might be a problem in Mol* itself. I'll open an issue

**Comment by a-r-j** [comment]
Hi @hekima31 

Looks like your files are actually missing the number of atoms and the comment line at the start: https://github.com/molstar/molstar/issues/306

**Comment by hekima31** [comment]
Thank you @a-r-j ! It works now. 
Thank you for this fantastic project!
