### ISSUE TITLE
Installing on VSCode

### ISSUE THREAD

**Issue by dangthatsright** [a-r-j/VSCoding-Sequence#4]
Thanks for this, it looks very cool and I want to try to use it. Unfortunately I cannot install it on my VS Code. Do you know what version of VSCode this package is compatible with? I've googled and it says to look for a packages.json file but I'm not sure where to find that. 

Apparently I'm on 1.59.1 if that helps. 

Thanks!

**Comment by a-r-j** [comment]
Hi @dangthatsright thanks for getting in touch :)

We require VSCode 1.62.0+ (https://github.com/a-r-j/VSCoding-Sequence/blob/d3e23cc546ebf5d9257254dbd43e28ca4f008a04/package.json#L12)

I can’t recall if there’s a specific reason for requiring this version but I suspect there may have been one. Can you try updating VSCode and see if that helps?

**Comment by dangthatsright** [comment]
excellent, thanks a lot!
